### PR TITLE
Added ability to run MailMerge as a context manager

### PR DESCRIPTION
**Pull request by sliverc**
This fixes the resource leak problem as caller can open mailmerge with the with statement which then makes sure that zip file is closed.

This is actually a fairly critical change when using MailMerge on a server (as we do) when lots of zip/docx files are being opened but it is not guaranteed that they are closed.

### CODE REVIEW

**Comment by sliverc** [comment]
https://github.com/Bouke/docx-mailmerge/pull/30 needs to be merged first before CI will run on this PR.

**Comment by Bouke** [comment]
Thank you for your contribution. What strikes me as odd about this issue (memory leak), is that I feel like this should be handled by garbage collection. Once there are no references to the object MailMerge, it can be destructed and thus there will be no more references tot he ZipFile, which can be destructed and no memory should leak. Or am I missing something here?

**Comment by sliverc** [comment]
This is not guaranteed in case of resources. See discussion here as a summary: https://stackoverflow.com/questions/7395542/is-explicitly-closing-files-important?answertab=votes#tab-top

What this PR does giving the ability to run MailMerge in a context manager when needed. If someone doesn't see a need in his use case MailMerge still works as before without closing so this change is 100% backwards compatible.

**Comment by Bouke** [comment]
Thank you for the clarification, looks like a great stability improvement to add. 👍

**Pull request merged**
