### PR TITLE
Issue #77: Fixed merge_templates method performance

### PR DESCRIPTION
**Pull request by lyzohub**
## Description
It seems that every time we loop through all the pages, and the complexity increases exponentially. I make some performance test with different count of templates, attached screenshot. Moved the initialization of the parts list to fix this problem.

## Motivation and Context
Fix issue #77 
During project development, I ran into performance issues with a lot of templates.

## How Has This Been Tested?
Tested on local files. 
All unit test are passed.

## Screenshots (if appropriate):
Seconds/Template count
Screen Shot 2020-07-03 at 11 02 56 PM
Screen Shot 2020-07-03 at 10 37 26 PM
Screen Shot 2020-07-03 at 10 34 14 PM
Screen Shot 2020-07-03 at 10 34 54 PM
Screen Shot 2020-07-03 at 10 40 07 PM
Screen Shot 2020-07-03 at 10 36 28 PM
After fix:
Screen Shot 2020-07-03 at 11 05 35 PM
Screen Shot 2020-07-03 at 11 04 50 PM

unit tests
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ngoonee** [comment]
Any reason this was closed? I just happened to be browsing and saw this is a really minor change.

**Comment by lyzohub** [comment]
@ngoonee I closed this due to ignore.

**Comment by ngoonee** [comment]
@lyzohub I think it can be left open, as closing normally indicates this is no longer a problem. If/when the maintainer comes back an open issue is much more likely to result in improvement.

**Comment by Bouke** [comment]
Thank you for your contribution!

**Comment by timnyborg** [comment]
Thanks very much for the fix, @lyzohub 
@Bouke, any idea when a new release version may happen?  I'd love to get this in production.

**Comment by pathakh** [comment]
^ we need this into the version update please.

**Pull request merged**
